theme: jekyll-theme-minimal
title: BDA-503 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Emirhan's Journal
description: Welcome to my journal, this is Emirhan
author : Emirhan Şahin
navbar-links:
  Greetings: "greetings"
  Assignments:
    - Assignment 1: "assignment1"
  Contact: "contact"
